### ISSUE TITLE
0.1.5 fails to migrate

### ISSUE THREAD

**Issue by iainhouston** [bitmazk/cmsplugin-markdown#12]
From a standard `djangocms` installation with only `cmsplugin_markdown` and `django-epiceditor` additionally installed. See below for all packages and versions.

```
$ pip install -r requirements.txt --upgrade
  Requirement already up-to-date: cmsplugin-filer==1.1.3 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 1))
  Obtaining cmsplugin_markdown from git+git://github.com/bitmazk/cmsplugin-markdown.git@91064b93b2feac992358d740245eb06e586c4a6e#egg=cmsplugin_markdown (from -r requirements.txt (line 2))
    Skipping because already up-to-date.
  Requirement already up-to-date: dj-database-url==0.4.1 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 3))
  Requirement already up-to-date: Django==1.10.2 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 4))
  Requirement already up-to-date: django-appconf==1.0.2 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 5))
  Requirement already up-to-date: django-classy-tags==0.8.0 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 6))
  Requirement already up-to-date: django-cms==3.4.1 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 7))
  Requirement already up-to-date: django-epiceditor==0.2.3 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 8))
  Requirement already up-to-date: django-filer==1.2.5 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 9))
  Requirement already up-to-date: django-formtools==1.0 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 10))
  Requirement already up-to-date: django-markwhat==1.5 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 11))
  Requirement already up-to-date: django-mptt==0.8.6 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 12))
  Requirement already up-to-date: django-polymorphic==0.8.1 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 13))
  Requirement already up-to-date: django-sekizai==0.10.0 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 14))
  Requirement already up-to-date: Django-Select2==4.3.2 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 15))
  Requirement already up-to-date: django-treebeard==4.0.1 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 16))
  Requirement already up-to-date: djangocms-admin-style==1.2.6 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 17))
  Requirement already up-to-date: djangocms-attributes-field==0.1.1 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 18))
  Requirement already up-to-date: djangocms-column==1.7.0 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 19))
  Requirement already up-to-date: djangocms-googlemap==0.5.2 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 20))
  Requirement already up-to-date: djangocms-installer==0.9.1 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 21))
  Requirement already up-to-date: djangocms-link==2.0.1 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 22))
  Requirement already up-to-date: djangocms-snippet==1.9.1 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 23))
  Requirement already up-to-date: djangocms-style==1.7.0 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 24))
  Requirement already up-to-date: djangocms-text-ckeditor==3.3.0 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 25))
  Requirement already up-to-date: djangocms-video==2.0.2 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 26))
  Requirement already up-to-date: easy-thumbnails==2.3 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 27))
  Requirement already up-to-date: html5lib==0.9999999 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 28))
  Requirement already up-to-date: Markdown==2.6.7 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 29))
  Requirement already up-to-date: Pillow==3.4.2 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 30))
  Requirement already up-to-date: pytz==2016.7 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 31))
  Requirement already up-to-date: six==1.10.0 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 32))
  Requirement already up-to-date: tzlocal==1.3 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 33))
  Requirement already up-to-date: Unidecode==0.4.19 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from -r requirements.txt (line 34))
  Requirement already up-to-date: setuptools in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from django-polymorphic==0.8.1->-r requirements.txt (line 13))
  Requirement already up-to-date: argparse in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from djangocms-installer==0.9.1->-r requirements.txt (line 21))
  Requirement already up-to-date: pip in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from djangocms-installer==0.9.1->-r requirements.txt (line 21))
  Installing collected packages: cmsplugin-markdown
    Running setup.py develop for cmsplugin-markdown
  Successfully installed cmsplugin-markdown-0.1.5

  $ egrep -n 'APP|mark|epic' mycms/settings.py 
  44:WSGI_APPLICATION = 'mycms.wsgi.application'
  124:INSTALLED_APPS = (
  125:    'epiceditor',
  126:    'django_markwhat',
  127:    'cmsplugin_markdown',

  $ ./manage.py migrate 
  Traceback (most recent call last):
    File "./manage.py", line 10, in <module>
      execute_from_command_line(sys.argv)
    File "/Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
      utility.execute()
    File "/Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
      django.setup()
    File "/Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
      apps.populate(settings.INSTALLED_APPS)
    File "/Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
      app_config.import_models(all_models)
    File "/Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
      self.models_module = import_module(models_module_name)
    File "/Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 986, in _gcd_import
    File "<frozen importlib._bootstrap>", line 969, in _find_and_load
    File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 665, in exec_module
    File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
    File "/Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages/filer/models/__init__.py", line 3, in <module>
      from .clipboardmodels import *  # flake8: noqa
    File "/Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages/filer/models/clipboardmodels.py", line 9, in <module>
      from . import filemodels
    File "/Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages/filer/models/filemodels.py", line 43, in <module>
      class File(PolymorphicModel, mixins.IconsMixin):
    File "/Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages/polymorphic/base.py", line 74, in __new__
      inherited_managers = new_class.get_inherited_managers(attrs)
    File "/Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages/polymorphic/base.py", line 148, in get_inherited_managers
      if manager._inherited:
  AttributeError: 'Manager' object has no attribute '_inherited'
```

**Comment by Tyrdall** [comment]
@iainhouston This is not an issue of this app. Please check django-polymorphic or django-filer for this error.
